version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 5.0
    commands:
      - echo Installing dependencies...
      - dotnet restore
  build:
    commands:
      - echo Building the application...
      - dotnet build --configuration Release
      - dotnet publish --configuration Release --output $CODEBUILD_SRC_DIR/publish
artifacts:
  files:
    - '**/*'
    - '!bin/**/*'
    - '!obj/**/*'
  base-directory: '$CODEBUILD_SRC_DIR/publish'
  discard-paths: yes

cache:
  paths:
    - ~/.nuget/packages

# Deployment actions
# Update the AWS_REGION and AWS_ACCOUNT_ID with your own region and account ID
# Set up your environment variables on the AWS CodePipeline console
# Set up a Beanstalk environment and deploy an application
# Refer to the AWS documentation for more details: https://docs.aws.amazon.com/codepipeline/latest/userguide/tutorials-ecs-ecr-codedeploy.html

deploy:
  SocialMediaAppBeanstalk:
    provider: ElasticBeanstalk
    region: AWS_REGION
    app_name: SocialMediaApp
    env_name: SocialMediaAppEnv
    bucket_name: aws-codedeploy-ACCOUNT_ID
    bucket_path: SocialMediaApp
    zip_file: ./SocialMediaApp.zip
    artifact: SocialMediaApp
    wait-until-deployed: true
    on:
      branch: master
