version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 3.1
    commands:
      - echo Installing dependencies...
      - dotnet restore

  build:
    commands:
      - echo Building the application...
      - dotnet build --configuration Release

  post_build:
    commands:
      - echo Publishing the application...
      - dotnet publish --configuration Release --output $CODEBUILD_SRC_DIR/publish

artifacts:
  files:
    - '**/*'
  base-directory: $CODEBUILD_SRC_DIR/publish
